baseURL = "https://2mol.netlify.com/"
languageCode = "en-us"
title = "2mol"
theme = "2mol"

enableGitInfo = true

disableKinds = ["taxonomy", "taxonomyTerm"]

googleAnalytics = "UA-134695331-1"

[params]
  githubURL = "https://github.com/2mol/"
  githubEditURL = "https://github.com/2mol/site/edit/master/content/"
  dateFormat = "2006-01-02"
